name: Generate Podcast

on:
  schedule:
    - cron: '0 1 * * *'  # 每天北京时间 9 点运行
  workflow_dispatch:      # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:         # 添加权限设置
      contents: write    # 允许写入仓库内容
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate podcast
      run: python scripts/generate_podcast.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
    
    - name: Check API Key
      run: |
        if [ -n "$API_KEY" ]; then
          echo "API Key is set (showing first 10 characters): ${API_KEY:0:10}..."
        else
          echo "API Key is not set!"
        fi
      env:
        API_KEY: ${{ secrets.API_KEY }}
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web/public
        force_orphan: true