name: Generate Podcast

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00，即北京时间 8:00 运行
  workflow_dispatch:      # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:         
      contents: write    
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages  # 首先检出 gh-pages 分支
        path: gh-pages  # 将其检出到 gh-pages 目录
        
    - uses: actions/checkout@v2
      with:
        path: main  # 将主分支检出到 main 目录
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # 更新到 actions/cache@v3
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('main/**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r main/requirements.txt
    
    - name: Copy existing podcasts
      run: |
        if [ -d "gh-pages/podcasts" ]; then
          mkdir -p main/web/public/podcasts
          cp -r gh-pages/podcasts/* main/web/public/podcasts/
        fi
        if [ -f "gh-pages/podcast_index.json" ]; then
          cp gh-pages/podcast_index.json main/web/public/
        fi
    
    - name: Generate podcast
      run: |
        cd main
        python scripts/generate_podcast.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
        VOLC_ACCESS_TOKEN: ${{ secrets.VOLC_ACCESS_TOKEN }}
    
    - name: Check API Key
      run: |
        if [ -n "$API_KEY" ]; then
          echo "API Key is set (showing first 10 characters): ${API_KEY:0:10}..."
        else
          echo "API Key is not set!"
        fi
      env:
        API_KEY: ${{ secrets.API_KEY }}
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./main/web/public
        keep_files: true  # 保留现有文件